name: 'Layout field storage'
description: 'Installs Layout Builder field storage and Layout Builder Restrictions.'
type: 'Field storage'
install:
# Core
  - layout_builder
  - layout_discovery
  - node
# Contrib
  - layout_builder_admin_theme
  - layout_builder_restrictions
  - paragraphs
  